### PR TITLE
feat: junction-saturation

### PR DESCRIPTION
**Pull request by a-frantz**
This is not as efficient as it could be, but it took the least amount of changes to the existing `junction-annotation` code. I could get a substantial speed up if I rewrite `junction-annotation`, but I didn't think it was worth the development time. (And the faster implementation will come at the cost of higher memory usage)

### CODE REVIEW

**Comment by a-frantz** [comment]
@claymcleod this is what the RSeQC graph looks like. I don't think it's possible to intuitively chart all 3 categories on the same figure when dealing with multiple samples. Do you think generating 3 graphs for each of "known/partial/novel" is the right approach? We'd have to ensure the colors are the same for each sample, and probably the scale as well. There should be a way in MultiQC to render all 3 next to each other horizontally.
Screen Shot 2021-11-05 at 2 50 58 PM

**Comment by claymcleod** [comment]
Yeah I think that’s a fine first step (the three graphs).

**Comment by a-frantz** [comment]
@claymcleod a bot pinged me about this saying it was stale (which it definitely is). Looks like this is fully implemented, _might_ need a tweak or two after the updates to `master` (haven't reviewed that closely). It also needs docs written for it before it could be merged.

I think the reason this wasn't merged earlier was because we were waiting for a multiqc integration? What do you think, should we go ahead merge this new command? If yes, do you want to see this implemented in MultiQC/`v2` of the QC pipeline soon? Or can it wait? My gut instinct is that this would be labelled "Nice to Have", but not integral to `v2`.

Regardless, I think we can go ahead and add this new command without waiting on either integration.

**Comment by claymcleod** [comment]
Yeah I agree

**Comment by a-frantz** [comment]
Alright I'll make sure it's working correctly, then write up some docs, and we can merge this in!

**Review by claymcleod — APPROVED** [review]
I did a quick review, but looks good.

**Pull request merged**
